---
title: "Untitled"
author: "Oleksii Kocheriev"
date: "04/12/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}
my_data <- read.csv("California_Fire_Incidents.csv")
my_data[is.na(my_data)]<- 0

#dependence between helicopters involved and injuries

d5 <- subset(my_data, Helicopters >0 & Injuries > 0, select = c(Helicopters, Injuries))

#dependence between crew members involved and injuries
d6 <- subset(my_data, CrewsInvolved >0 & Injuries > 0, select = c(CrewsInvolved, Injuries))

library(ggplot2)

#install.packages("gridExtra") #installing given package
library("gridExtra")

lr1 <- ggplot(d5, aes(x = Helicopters, y = Injuries)) + geom_point() + geom_smooth(method = "lm", formula = y ~ x) + labs(title = "Dependence of Helicopters and Injuries", subtitle = " Linear regression")

pr1 <-  ggplot(d5, aes(x = Helicopters, y = Injuries)) + geom_point() + geom_smooth(method = "lm", formula = y ~ poly(x, 7)) + labs(title = "Dependence of Helicopters and Injuries", subtitle = "Polynomial regression with power of 7")



pr2 <- ggplot(d6, aes(x = CrewsInvolved, y = Injuries)) + geom_point() + geom_smooth(method = "lm", formula = y ~ poly(x, 3)) + labs(title = "Dependence of Crews Involved and Injuries", x = "Crews Involved", subtitle = "Polynomial regression with power of 3")


lr2 <- ggplot(d6, aes(x = CrewsInvolved, y = Injuries)) + geom_point() + geom_smooth(method = "lm", formula = y ~ x) + labs(title = "Dependence of Crews Involved and Injuries", subtitle = "Linear regression", x = "Crews Involved")

grid.arrange(lr1,pr1, nrow = 2, ncol = 1)

grid.arrange(lr2,pr2, nrow = 2, ncol = 1)


######




```





























